site_name: Field Friend Software Documentation
site_url: https://docs.feldfreund.de/
nav:
  - index.md
  - getting_started.md
  - Features:
      - features/user_interface.md # NOTE: shown when clicking on "Examples" folder
      - features/user_interface.md
      - features/field_creator.md
      - features/developer_interface.md
  - Module Reference: reference/
  - contributing.md
  - troubleshooting.md
repo_url: https://github.com/zauberzeug/field_friend
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Source Sans Pro
  features:
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - def_list
  - mdx_include:
      base_path: docs
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - footnotes
plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate_reference.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - macros:
      module_name: docs/run_macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            merge_init_into_class: true
            separate_signature: true
watch:
  - field_friend
