from rosys.geometry import Pose

from field_friend.config.configuration import (  # ImuConfiguration,
    BumperConfiguration,
    CameraConfiguration,
    CircleSightPositions,
    CropConfiguration,
    FieldFriendConfiguration,
    FlashlightConfiguration,
    GnssConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    TornadoConfiguration,
    WheelsConfiguration,
    YCanOpenConfiguration,
)

config = FieldFriendConfiguration(
    name='fieldfriend-f13',
    robot_brain=RobotBrainConfiguration(name='rb36', flash_params=['orin', 'v05', 'nand'], enable_esp_on_startup=True),
    tool='tornado',
    measurements=MeasurementsConfiguration(
        tooth_count=15,
        pitch=0.033,
        work_x=0.035,
        work_y=0.0,
    ),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        crop=CropConfiguration(left=60, right=200, up=20, down=0),
    ),
    circle_sight_positions=CircleSightPositions(
        right='-1',
        back='-2',
        front='-3',
        left='-4',
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=False,
        is_right_reversed=True,
        left_back_can_address=0x000,
        left_front_can_address=0x100,
        right_back_can_address=0x200,
        right_front_can_address=0x300,
    ),
    has_status_control=True,
    flashlight=FlashlightConfiguration(
        version='flashlight_pwm_v2',
        front_pin=22,
        back_pin=23,
        on_expander=True,
    ),
    bumper=BumperConfiguration(
        pin_front_top=35,
        pin_front_bottom=18,
        pin_back=21,
        on_expander=True,
    ),
    y_axis=YCanOpenConfiguration(
        axis_offset=0.0675,
        reversed_direction=False,
        end_left_pin=13,
        end_right_pin=4,
        end_stops_on_expander=False,
        motor_on_expander=False,
        can_address=0x60,
        end_stops_inverted=True,
        max_speed=450,
        reference_speed=40,
        steps_per_m=1_481_481.48,
        name='yaxis',
        max_position=0.0625,
        min_position=-0.0625,
        version='y_axis_canopen',
    ),
    z_axis=TornadoConfiguration(
        end_stops_on_expander=False,
        motor_on_expander=False,
        end_bottom_pin=4,
        end_bottom_pin_expander=True,
        end_top_pin=33,
        end_top_pin_expander=True,
        name='tornado',
        max_position=0.0,
        min_position=-0.085,
        version='tornado',
        ref_gear_pin=36,
        ref_knife_stop_pin=5,
        ref_knife_stop_pin_expander=True,
        ref_knife_ground_pin=32,
        ref_knife_ground_pin_expander=True,
        ref_motor_pin=5,
        turn_speed_limit=1.5,
    ),
    gnss=GnssConfiguration(antenna_pose=Pose(x=0.041, y=-0.255, yaw=0.0)),
    # TODO: add IMU, when the next stable version is released
    # ImuConfiguration(offset_rotation=Rotation.from_euler(0.0, 0, 0))
    imu=None,
)
