from rosys.geometry import Pose, Rotation

from field_friend.config.configuration import (
    BumperConfiguration,
    CameraConfiguration,
    CircleSightPositions,
    CropConfiguration,
    FieldFriendConfiguration,
    FlashlightConfiguration,
    GnssConfiguration,
    ImuConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    WheelsConfiguration,
    AxisD1Configuration,
)

config = FieldFriendConfiguration(
    name='fieldfriend-f15',
    robot_brain=RobotBrainConfiguration(name='rb52', flash_params=['orin', 'v05', 'nand'], enable_esp_on_startup=False),
    tool='weed_screw',
    measurements=MeasurementsConfiguration(
        tooth_count=15,
        pitch=0.033,
        work_x=0.086,
        work_y=0.0096,
        wheel_distance=0.47,
    ),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        crop=CropConfiguration(left=150, right=150, up=40, down=0),
    ),
    circle_sight_positions=CircleSightPositions(
        right='-1',
        back='-2',
        front='-3',
        left='-4',
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=False,
        is_right_reversed=True,
        left_back_can_address=0x000,
        left_front_can_address=0x100,
        right_back_can_address=0x200,
        right_front_can_address=0x300,
        odrive_version=6,
    ),
    has_status_control=True,
    flashlight=FlashlightConfiguration(
        version='flashlight_pwm_v2',
        front_pin=12,
        back_pin=23,
        on_expander=True,
    ),
    bumper=BumperConfiguration(
        pin_front_top=18,
        pin_front_bottom=35,
        pin_back=21,
        on_expander=True,
    ),
    y_axis=AxisD1Configuration(
        version='axis_d1',
        name='yaxis',
        can_address=0x60,
        homing_acceleration=2000,
        homing_velocity=400,
        profile_acceleration=100000,
        profile_velocity=25000,
        profile_deceleration=100000,
        min_position=-0.11,
        max_position=0.11,
        axis_offset=0.115,
        reversed_direction=False,
    ),
    z_axis=AxisD1Configuration(
        version='axis_d1',
        name='zaxis',
        can_address=0x70,
        homing_acceleration=1000,
        homing_velocity=500,
        profile_acceleration=500000,
        profile_velocity=40000,
        profile_deceleration=500000,
        min_position=-0.230,
        max_position=0,
        axis_offset=-0.01,
        reversed_direction=True,
    ),
    gnss=GnssConfiguration(antenna_pose=Pose(x=0.072, y=-0.255, yaw=0.0)),
    imu=ImuConfiguration(offset_rotation=Rotation.from_euler(-1.570796, 0, 0)),
)
