from rosys.geometry import Pose, Rotation

from field_friend.config.configuration import (
    CameraConfiguration,
    FieldFriendConfiguration,
    GnssConfiguration,
    ImuConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    WheelsConfiguration,
    YStepperConfiguration,
    ZStepperConfiguration,
)

config = FieldFriendConfiguration(
    name='field-friend-f3',
    robot_brain=RobotBrainConfiguration(name='rb26', flash_params=['']),
    tool='weed_screw',
    measurements=MeasurementsConfiguration(tooth_count=17, pitch=0.041, work_x=0.118),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        fps=10,
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=False,
        is_right_reversed=True,
        left_front_can_address=0x000,
        right_front_can_address=0x100,
        left_back_can_address=0x001,
        right_back_can_address=0x101,
        name='wheels',
        version='wheels',
    ),
    has_status_control=False,
    flashlight=None,
    bumper=None,
    y_axis=YStepperConfiguration(
        axis_offset=0.123,
        reversed_direction=False,
        end_stops_on_expander=True,
        motor_on_expander=False,
        end_left_pin=21,
        end_right_pin=35,
        name='y_axis',
        max_position=0.12,
        min_position=-0.12,
        version='y_axis_stepper',
        alarm_inverted=False,
        alarm_pin=13,
        step_pin=5,
        direction_pin=4,
        max_speed=80_000,
        reference_speed=16_000,
        steps_per_m=666.7*1000,
        end_stops_inverted=True,
    ),
    z_axis=ZStepperConfiguration(
        name='z_axis',
        version='z_axis_stepper',
        reversed_direction=True,
        end_stops_on_expander=True,
        motor_on_expander=True,
        axis_offset=0.0,
        min_position=-0.197,
        max_position=0.00,
        end_bottom_pin=22,
        end_top_pin=25,
        alarm_pin=33,
        step_pin=5,
        direction_pin=4,
        max_speed=60_000,
        reference_speed=20_000,
        steps_per_m=1600*1000,
        end_stops_inverted=True,
    ),
    circle_sight_positions=None,
    gnss=GnssConfiguration(antenna_pose=Pose(x=0.041, y=-0.255, yaw=0.0)),  # this needs to be changed
    imu=None  # this needs to be changed
)
