from rosys.geometry import Pose, Rotation

from field_friend.config.configuration import (
    BumperConfiguration,
    CameraConfiguration,
    CircleSightPositions,
    CropConfiguration,
    FieldFriendConfiguration,
    FlashlightConfiguration,
    GnssConfiguration,
    ImuConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    TornadoConfiguration,
    WheelsConfiguration,
    YStepperConfiguration,
)

config = FieldFriendConfiguration(
    name='uckerbot-u4',
    robot_brain=RobotBrainConfiguration(name='rb28', flash_params=['orin'], enable_esp_on_startup=True),
    tool='tornado',
    measurements=MeasurementsConfiguration(tooth_count=17, pitch=0.041),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        crop=CropConfiguration(left=250, right=250, up=0, down=0),
    ),
    circle_sight_positions=CircleSightPositions(
        right='-2',
        left='-4',  # not sure, camera not working
        front='-3',
        back='-1',  # not sure, camera not working
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=False,
        is_right_reversed=True,
        left_back_can_address=0x000,
        left_front_can_address=0x100,
        right_back_can_address=0x200,
        right_front_can_address=0x300,
        odrive_version=6,
    ),
    has_status_control=True,
    flashlight=FlashlightConfiguration(
        version='flashlight_pwm',
        pin=2,
        on_expander=True,
        rated_voltage=23.0,
    ),
    bumper=BumperConfiguration(pin_front_top=12, pin_front_bottom=22, pin_back=25),
    y_axis=YStepperConfiguration(
        axis_offset=0.075,
        reversed_direction=False,
        end_stops_on_expander=True,
        motor_on_expander=False,
        end_stops_inverted=True,
        max_speed=60_000,
        reference_speed=10_000,
        steps_per_m=599_251,
        direction_pin=4,
        step_pin=5,
        end_left_pin=21,
        end_right_pin=19,
        name='y_axis',
        max_position=0.068,
        min_position=-0.068,
        version='y_axis_stepper',
        alarm_inverted=True,
        alarm_pin=13,
    ),
    z_axis=TornadoConfiguration(
        end_stops_on_expander=True,
        motor_on_expander=False,
        end_bottom_pin=5,
        end_top_pin=32,
        name='tornado',
        max_position=0.0,
        min_position=-0.09,
        version='tornado',
        ref_gear_pin=4,
        ref_knife_ground_pin=18,
        ref_knife_stop_pin=35,
        ref_motor_pin=33,
        turn_speed_limit=1.3,
        odrive_version=6,
    ),
    gnss=GnssConfiguration(antenna_pose=Pose(x=0.041, y=-0.255, yaw=0.0)),
    imu=ImuConfiguration(offset_rotation=Rotation.from_euler(-1.570796, 0, 0)),
)
