from rosys.geometry import Rotation

from field_friend.config.configuration import (
    BumperConfiguration,
    CameraConfiguration,
    CircleSightPositions,
    FieldFriendConfiguration,
    FlashlightConfiguration,
    GnssConfiguration,
    ImuConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    WheelsConfiguration,
    YCanOpenConfiguration,
    ZCanOpenConfiguration,
)

config = FieldFriendConfiguration(
    name='uckerbot-u6',
    robot_brain=RobotBrainConfiguration(name='rb34',
                                        flash_params=['orin', 'v05'],
                                        enable_esp_on_startup=True,
                                        use_espresso=True),
    tool='weed_screw',
    measurements=MeasurementsConfiguration(tooth_count=17, pitch=0.041, work_x=0.085),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        fps=10,
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=True,
        is_right_reversed=False,
        left_back_can_address=0x000,
        left_front_can_address=0x100,
        right_back_can_address=0x200,
        right_front_can_address=0x300,
        odrive_version=6
    ),
    has_status_control=True,
    flashlight=FlashlightConfiguration(
        version='flashlight_pwm_v2',
        on_expander=False,
        front_pin=5,
        back_pin=4,
    ),
    bumper=BumperConfiguration(pin_front_top=35, pin_front_bottom=18, pin_back=21),
    y_axis=YCanOpenConfiguration(
        axis_offset=0.13,
        reversed_direction=False,
        end_left_pin=25,
        end_right_pin=12,
        end_stops_on_expander=True,
        motor_on_expander=False,
        can_address=0x70,
        end_stops_inverted=True,
        max_speed=300,
        reference_speed=30,
        steps_per_m=1_666_666.667,  # 4000steps/turn motor; 1/10 gear; 0.024m/u
        name='yaxis',
        max_position=0.125,
        min_position=-0.125,
        version='y_axis_canopen',
    ),
    z_axis=ZCanOpenConfiguration(
        axis_offset=0.0,
        reversed_direction=False,
        end_stops_on_expander=True,
        motor_on_expander=False,
        end_bottom_pin=23,
        end_top_pin=22,
        can_address=0x60,
        end_stops_inverted=True,
        max_speed=400,
        reference_speed=30,
        steps_per_m=4_000_000,  # 4000steps/turn motor; 1/20 gear; 0.02m/u
        name='zaxis',
        max_position=0.0,
        min_position=-0.197,
        version='z_axis_canopen',
    ),
    circle_sight_positions=CircleSightPositions(
        right='-1',
        back='-3',
        front='-2',
        left='-4',
    ),
    gnss=GnssConfiguration(),
    imu=ImuConfiguration(offset_rotation=Rotation.from_euler(-1.597158, 0.022681, 1.570198)),
)
