from .configuration import (
    BumperConfiguration,
    CameraConfiguration,
    FieldFriendConfiguration,
    FlashlightConfiguration,
    MeasurementsConfiguration,
    RobotBrainConfiguration,
    WheelsConfiguration,
    YCanOpenConfiguration,
    ZCanOpenConfiguration,
)

config = FieldFriendConfiguration(
    name='uckerbot-u6',
    robot_brain=RobotBrainConfiguration(name='rb28', flash_params=['orin', 'v05']),
    tool='weed_screw',
    measurements=MeasurementsConfiguration(tooth_count=17, pitch=0.041, work_x=0.085),
    camera=CameraConfiguration(
        width=1280,
        height=720,
        fps=10,
    ),
    wheels=WheelsConfiguration(
        is_left_reversed=False,
        is_right_reversed=True,
        left_back_can_address=0x000,
        left_front_can_address=0x100,
        right_back_can_address=0x200,
        right_front_can_address=0x300,
    ),
    has_status_control=True,
    flashlight=FlashlightConfiguration(
        version='flashlight_pwm_v2',
        on_expander=False,
        front_pin=5,
        back_pin=4,
    ),
    bumper=BumperConfiguration(pin_front_top=35, pin_front_bottom=18, pin_back=21),
    y_axis=YCanOpenConfiguration(
        axis_offset=0.13,
        reversed_direction=False,
        end_l_pin=25,
        end_r_pin=12,
        end_stops_on_expander=True,
        motor_on_expander=False,
        can_address=0x70,
        end_stops_inverted=True,
        max_speed=300,
        reference_speed=30,
        steps_per_m=1_666_666.667,  # 4000steps/turn motor; 1/10 gear; 0.024m/u
        name='yaxis',
        max_position=0.125,
        min_position=-0.125,
        version='y_axis_canopen',
    ),
    z_axis=ZCanOpenConfiguration(
        axis_offset=0.0,
        reversed_direction=False,
        end_stops_on_expander=True,
        motor_on_expander=False,
        end_bottom_pin=23,
        end_top_pin=22,
        can_address=0x60,
        end_stops_inverted=True,
        max_speed=400,
        reference_speed=30,
        steps_per_m=4_000_000,  # 4000steps/turn motor; 1/20 gear; 0.02m/u
        name='zaxis',
        max_position=0.0,
        min_position=-0.197,
        version='z_axis_canopen',
    ),
)
