# this is ff3
fieldfriend_configuration = {
    'params': {
        'motor_gear_ratio': 12.52,
        'thooth_count': 17,
        'pitch': 0.041,
        'wheel_distance': 0.47,
        'work_x': 0.118,
        'drill_radius': 0.025,
        'tool': 'none',
    },
    'robot_brain': {
        'flash_params': [],
    },
    'bluetooth': {
        'name': 'fieldfriend-ff3',
    },
    'serial': {
        'name': 'serial',
        'rx_pin': 26,
        'tx_pin': 27,
        'baud': 115200,
        'num': 1,
    },
    'expander': {
        'name': 'p0',
        'boot': 25,
        'enable': 14,
    },
    'can': {
        'name': 'can',
        'on_expander': False,
        'rx_pin': 32,
        'tx_pin': 33,
        'baud': 1_000_000,
    },
    'wheels': {
        'version': 'wheels',
        'name': 'wheels',
        'left_can_address': 0x000,
        'right_can_address': 0x100,
        'is_left_reversed': False,
        'is_right_reversed': True,
    },
    'y_axis': {
        'version': 'y_axis',
        'name': 'y_axis',
        'motor_on_expander': False,
        'end_stops_on_expander': True,
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 13,
        'end_l_pin': 21,
        'end_r_pin': 35,
    },
    'z_axis': {
        'version': 'z_axis_v2',
        'name': 'z_axis',
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 33,
        'ref_t_pin': 25,
        'end_b_pin': 22,
        'motor_on_expander': True,
        'end_stops_on_expander': True,
        'ref_t_inverted': True,
        'end_b_inverted':  False,
        'ccw': True,

    },
    'flashlight': {
        'version': 'none',
    },
    'estop': {
        'name': 'estop',
        'pins': {'1': 34, '2': 35},
    },
    'bms': {
        'name': 'bms',
        'on_expander': True,
        'rx_pin': 26,
        'tx_pin': 27,
        'baud': 9600,
        'num': 2,
    },
    'battery_control': {
        'name': 'battery_control',
        'on_expander': True,
        'reset_pin': 15,
        'status_pin': 13,
    },
}
