configuration = {'wheels': {
    'version': 'wheels',
    'name': 'wheels',
    'left_can_address': 0x000,
    'right_can_address': 0x100,
    'is_left_reversed': False,
    'is_right_reversed': True,
},
    'y_axis': {
        'version': 'y_axis_stepper',
        'name': 'y_axis',
        'max_speed': 80_000,
        'reference_speed': 15_000,
        'min_position': -0.12,
        'max_position': 0.12,
        'axis_offset': 0.123,
        'steps_per_m': 666.67 * 1000,
        'motor_on_expander': False,
        'end_stops_on_expander': True,
        'reversed_direction': False,
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 13,
        'end_l_pin': 21,
        'end_r_pin': 35,
},
    'z_axis': {
        'version': 'z_axis_stepper',
        'name': 'z_axis',
        'max_speed': 60_000,
        'reference_speed': 20_000,
        'min_position': -0.197,
        'max_position': 0.00,
        'axis_offset': 0.0,
        'steps_per_m': 1600 * 1000,
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 33,
        'end_t_pin': 25,
        'end_b_pin': 22,
        'motor_on_expander': True,
        'end_stops_on_expander': True,
        'reversed_direction': True,

},
    'flashlight': {
        'version': 'none',
},
    'estop': {
        'name': 'estop',
        'pins': {'1': 34, '2': 35},
},
    'bms': {
        'name': 'bms',
        'on_expander': True,
        'rx_pin': 26,
        'tx_pin': 27,
        'baud': 9600,
        'num': 2,
},
    'battery_control': {
        'name': 'battery_control',
        'on_expander': True,
        'reset_pin': 15,
        'status_pin': 13,
},
    'bluetooth': {
        'name': 'fieldfriend-ff3',
},
    'serial': {
        'name': 'serial',
        'rx_pin': 26,
        'tx_pin': 27,
        'baud': 115200,
        'num': 1,
},
    'expander': {
        'name': 'p0',
        'boot': 25,
        'enable': 14,
},
    'can': {
        'name': 'can',
        'on_expander': False,
        'rx_pin': 32,
        'tx_pin': 33,
        'baud': 1_000_000,
}
}
