configuration = {'wheels': {
    'version': 'wheels',
    'name': 'wheels',
    'left_can_address': 0x000,
    'right_can_address': 0x100,
    'is_left_reversed': False,
    'is_right_reversed': True,
},
    'y_axis': {
        'version': 'y_axis',
        'name': 'y_axis',
        'motor_on_expander': False,
        'end_stops_on_expander': True,
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 13,
        'end_l_pin': 21,
        'end_r_pin': 35,
},
    'z_axis': {
        'version': 'z_axis_v2',
        'name': 'z_axis',
        'step_pin': 5,
        'dir_pin': 4,
        'alarm_pin': 33,
        'ref_t_pin': 25,
        'end_b_pin': 22,
        'motor_on_expander': True,
        'end_stops_on_expander': True,
        'ref_t_inverted': True,
        'end_b_inverted':  False,
        'ccw': True,

},
    'flashlight': {
        'version': 'none',
},
    'estop': {
        'name': 'estop',
        'pins': {'1': 34, '2': 35},
},
    'bms': {
        'name': 'bms',
        'on_expander': True,
        'rx_pin': 26,
        'tx_pin': 27,
        'baud': 9600,
        'num': 2,
},
    'battery_control': {
        'name': 'battery_control',
        'on_expander': True,
        'reset_pin': 15,
        'status_pin': 13,
},
}
