name: Publish release

on:
  workflow_dispatch:
  push:
    tags:
      - v**
    # TODO: remove this before merging
    branches:
      - docu_update

jobs:
  docs:
    name: Build and publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # TODO: remove this before merging
        with:
          ref: docu_update
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r mkdocs_requirements.txt
          python3 -m pip install -e .
      - name: Build docs
        run: mkdocs build -v
      - name: Analyze
        run: |
          pwd
          ls -lha
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: site
      # TODO: restructure in another PR
      # - name: set version
      #   run: |
      #     VERSION=${{ env.VERSION }}
      # - name: Create GitHub release entry
      #   uses: softprops/action-gh-release@v2
      #   id: create_release
      #   with:
      #     draft: false
      #     prerelease: false
      #     name: ${{ env.VERSION }}
      #     tag_name: ${{ env.VERSION }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
