name: Run Tests

on: [push]

jobs:
  checker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e ".[dev]"
      - name: pre-commit, mypy & pylint
        run: |
          pre-commit run --all-files
          mypy ./field_friend --non-interactive
          pylint ./field_friend
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - run: pip install -r requirements.txt
      - run: pip install pytest pytest-asyncio
      - name: run pytests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest
