name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.2.2"
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
      - name: run pytests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -v -s --tb=short --show-capture=all
